name: Publish to Page

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "main" branch
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
          
        - name: Install Rust minimal nightly
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly
          run: rustup +nightly component add rust-src
          run: rustup +nightly target add wasm32-unknown-unknown

        - name: Install Just
          uses: extractions/setup-just@v1
            
        - name: Get Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            cache: true
            
        - name: Get dependencies
          run: flutter pub get
        - name: Gegnerate Flutter-Rust bindings
          run: just
        - name: Run Flutter tests
          run: flutter test
        - name: Build for web
          run: flutter build web