name: Web/GH Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - run: chmod -c -R +rX "web/"
    - uses: actions/download-artifact@master
      with:
        name: web
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        # Justfile
        - uses: extractions/setup-just@v1

        - name: Install LLVM and Clang
          uses: KyleMayes/install-llvm-action@v1
          with:
            version: "14.0"
        - name: Symlink libclang.so (Linux)
          if: contains(matrix.os, 'ubuntu')
          run: sudo ln -s libclang-14.so.1 /lib/x86_64-linux-gnu/libclang.so
          working-directory: ${{ env.LLVM_PATH }}/lib
          
        - name: Install Rust minimal nightly
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly
            components: rustfmt, rust-src
        # - run: rustup +nightly component add rust-src
        - run: rustup +nightly target add wasm32-unknown-unknown

        - name: Set up cargo cache
          uses: actions/cache@v3
          continue-on-error: false
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: ${{ runner.os }}-cargo-

        - name: Install Bridge codegen tools
          run: |
            cargo +nightly install cargo-expand flutter_rust_bridge_codegen || true
            cargo +nightly install wasm-pack wasm-bindgen-cli || true
            
        - name: Get Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            cache: true
            
        - name: Get dependencies
          run: flutter pub get
        - name: Gegnerate Flutter-Rust bindings
          run: just gen-gh
          
        - name: Build for web
          run: sh ./build_web.sh

        - name: Upload artifact
          uses: actions/upload-artifact@master
          with:
            name: web
            path: build/web
            if-no-files-found: error